In [1]:
import pandas as pd
import numpy as np
import gensim
from gensim import corpora
import pickle
import re
from spacy.lang.en.stop_words import STOP_WORDS
from collections import Counter
from nltk.corpus import wordnet
import nltk
from nltk.tokenize import word_tokenize 
from nltk.stem import WordNetLemmatizer 
# import dask.dataframe as dd
# from dask.multiprocessing import get
import swifter
from tqdm import tqdm

tqdm.pandas()
lemmatizer = WordNetLemmatizer() 

In [2]:
wordnet_map = {"N":wordnet.NOUN, "V":wordnet.VERB, "J":wordnet.ADJ, "R":wordnet.ADV}
def lemmatize_words(text):
    pos_tagged_text = nltk.pos_tag(text.split())
    return " ".join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_tagged_text])


In [3]:

url_pattern = re.compile(r'https?://\S+|www\.\S+')
alpha_pattern = re.compile(r'[^A-Za-z ]+')
def clean_up(x):
    x = url_pattern.sub(r'', x)
    x = alpha_pattern.sub(r'', x)
    word_tokens = word_tokenize(x.lower())
    filtered_sentence =[]
    for w in word_tokens:
        if len(w)<3 or w in STOP_WORDS:
            continue
        filtered_sentence.append(w.lower())
    x = []
    for word in filtered_sentence:
        x.append(lemmatize_words(word))
#         x.append(ps.stem(word))
    x = " ".join(x)
#     x = lemmatize_words(x)
    return x

In [4]:
df = pd.read_csv("data/drug_review/drugsComTrain_raw.tsv",delimiter="\t")[:11000]
test = pd.read_csv("data/drug_review/drugsComTest_raw.tsv",delimiter="\t")[:4000]
break_point = df.shape[0]

In [5]:
df.review = df.review.swifter.allow_dask_on_strings().apply((lambda row: clean_up(row)))

In [6]:
test.review = test.review.swifter.allow_dask_on_strings().apply(lambda row: clean_up(row))

In [7]:
reviews = pd.concat([df.review,test.review])

In [8]:
from collections import Counter
cnt = Counter()
for text in tqdm(reviews.values):
    old_words = []
    for word in text.split():
        if word not in old_words:
            cnt[word] += 1
            old_words.append(word)


100%|█████████████████████████████████████████████████████████████████████████| 15000/15000 [00:00<00:00, 37072.37it/s]


In [9]:
def remove_rare_freq_words(x):
    word_tokens = word_tokenize(x)
    x = []
    for w in word_tokens:
#         print("_*_"*100)
        if cnt[w] < high_pruner:
            x.append(w)
        elif cnt[w] > 20:
            x.append[w]
    x = " ".join(x)
    return x

In [10]:
high_pruner = reviews.shape[0]*0.65
reviews = reviews.progress_apply(lambda x : remove_rare_freq_words(x))
reviews[15]

100%|██████████████████████████████████████████████████████████████████████████| 15000/15000 [00:03<00:00, 4235.21it/s]


15    take saxenda july severe nausea month get dosa...
15    doctor prescribed provigil diagnose narcolepsy...
Name: review, dtype: object

In [11]:
clean_up("I happy had birthday too soon when where ok damn sorry after")

'happy birthday soon damn sorry'

#1. Dict
#2. Doc -> tokens token2id ##also remove duplicates
#3. Doc -> token_count 

In [12]:

texts = [[text for text in review.split()] for review in reviews]
dictionary = corpora.Dictionary(texts)
print(dictionary)

Dictionary(19856 unique tokens: ['bystolic', 'combination', 'effect', 'fish', 'oil']...)


In [13]:
df.review = reviews[:break_point]
test.review = reviews[break_point:]

In [14]:
def prepare_df(df,col="review"):
    df = pd.DataFrame(reviews,columns=[col])
    df["bow"] = df[col].apply(lambda x : dictionary.doc2bow(x.split(),))
    df["tokens"] = df.bow.apply(lambda x: np.array([[i[0] for i in x]]))
    df["counts"] = df.bow.apply(lambda x: np.array([[i[1] for i in x]]))
    df.drop(['bow','review'],axis=1,inplace=True)
    return df

In [15]:
df = prepare_df(df)
df.head()

tokens  \
0                                  [[0, 1, 2, 3, 4]]   
1  [[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1...   
2  [[2, 12, 21, 22, 37, 41, 43, 44, 48, 50, 51, 5...   
3  [[12, 62, 71, 74, 81, 82, 83, 84, 85, 86, 87, ...   
4  [[22, 23, 41, 49, 96, 97, 98, 99, 100, 101, 10...   

                                              counts  
0                                  [[1, 1, 1, 1, 1]]  
1  [[1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1,...  
2  [[2, 2, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1,...  
3  [[3, 1, 1, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,...  
4  [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...

In [16]:
train , valid = df.iloc[:int(df.shape[0]*0.9),:],df.iloc[int(df.shape[0]*0.9):,:]
print(train.shape)
print(valid.shape)

(13500, 2)
(1500, 2)


In [17]:
test = prepare_df(test)
print(test.shape)
test.head()

(15000, 2)


tokens  \
0                                  [[0, 1, 2, 3, 4]]   
1  [[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1...   
2  [[2, 12, 21, 22, 37, 41, 43, 44, 48, 50, 51, 5...   
3  [[12, 62, 71, 74, 81, 82, 83, 84, 85, 86, 87, ...   
4  [[22, 23, 41, 49, 96, 97, 98, 99, 100, 101, 10...   

                                              counts  
0                                  [[1, 1, 1, 1, 1]]  
1  [[1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1,...  
2  [[2, 2, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1,...  
3  [[3, 1, 1, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,...  
4  [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...

In [18]:
test , test_1,test_2 = test.iloc[:int(test.shape[0]*0.5),:],test.iloc[int(test.shape[0]*0.5):int(test.shape[0]*0.75),:],test.iloc[int(test.shape[0]*0.75):,:]
print(test.shape)
print(test_1.shape)
print(test_2.shape)
# test_1_tokens = test['tokens_1']
# test_1_counts = test['counts_1']

(7500, 2)
(3750, 2)
(3750, 2)


In [45]:
df = pd.DataFrame()
df["review"] = reviews
print(df.shape)
df.dropna(inplace=True)
print(df.shape)
df.to_csv("data/drug_review/preprocessed_reviews.csv",index=None)

df = pd.read_csv("data/drug_review/preprocessed_reviews.csv")
df

(15000, 1)
(15000, 1)


review
0                   effect combination bystolic fish oil
1      son halfway fourth week intuniv concerned begi...
2      oral contraceptive pill cycle happy light peri...
3      time form birth control glad go patch month de...
4      suboxone completely turn life feel healthier e...
5      day start work rock hard erection experianced ...
6      pull cummed bit take plan hour later take preg...
7      abilify change life hope zoloft clonidine star...
8      problem keppera constant shake arm amp leg amp...
9      pill year doctor change chateal effective help...
10     medication week start work way currently heada...
11     take antidepressant year improvement moderate ...
12     crohn resection year ago remission recently ba...
13     little bit linger cough cold give trouble keep...
14     start nexplanon month ago minimal contraceptio...
15     take saxenda july severe nausea month get dosa...
16     drug work clear uti matter hr day course xmgda...
17     ive take amitriptyline january diagnose fibrom...
18     ive medicine sun manage hypomania mania bipola...
19     tasigna year time day tasigna work week remiss...
20     spring hospitalize pnuemonia diagnose lyme die...
21     insomnia horrible story begin pcp prescribe pr...
22     nexplanon job worry free sex thing period ligh...
23     live western australia disturbed comment cost ...
24     use cream come turn hooha burning ring fire wo...
25     prescribed dose course day take pill light lun...
26     write second review vaniqa start february year...
27     son diagnose grade try medication try med loos...
28     honestly take ativan year twice daily help too...
29     suffer include splitting head pain nausea vomi...
...                                                  ...
14970  horrible nausea daily medication ive take year...
14971  dont buy dont buyi believe yeast infection itc...
14972  bad acne like whitehead blemish lot epiduo wee...
14973  xanax save brink suffer panic disorder anxiety...
14974  esgic tablet get rid migraine highly recommend...
14975  hosp work week bad research trouble med long t...
14976  start cervidil contraction hit receive epidura...
14977  get skyla month ago insertion painful cramp ho...
14978  xarelto work thin blood allow clot reabsorptio...
14979  yeast infection monistat treatmentalthough lon...
14980  start suboxonesubutex work great craving withd...
14981  testosterone level start drop year ago time lo...
14982  loestrin month love fact period lot lighter lo...
14983  pill week want switch feel like battling depre...
14984  currently lithicarb take tablet take morning n...
14985  lunesta night find fall asleep easily wake eas...
14986  use medication gout dont think survive work fa...
14987  test dec start viral load count begin med begi...
14988  year age smoker didnt think hope habit slowly ...
14989  start take lyrica nerve damage suffer surgery ...
14990  daughter adhd high level agression medicine fa...
14991  currently pill make lightheaded extremely naus...
14992  get skyla ive month come tomorrow absolutely t...
14993  restless leg syndrome year take lot different ...
14994  accutane give completely clear skin month year...
14995  finally found mixed buspar effective day sever...
14996  have problem birthcontrol clear acnemost didnt...
14997  month postinsertioncramps bad come theyrsquore...
14998  take linz week iti have terrible head pain fee...
14999  miracle drug like share comment take month cur...

[15000 rows x 1 columns]

In [21]:
train

tokens  \
0                                     [[0, 1, 2, 3, 4]]   
1     [[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1...   
2     [[2, 12, 21, 22, 37, 41, 43, 44, 48, 50, 51, 5...   
3     [[12, 62, 71, 74, 81, 82, 83, 84, 85, 86, 87, ...   
4     [[22, 23, 41, 49, 96, 97, 98, 99, 100, 101, 10...   
5     [[2, 12, 41, 48, 93, 140, 141, 142, 143, 144, ...   
6     [[28, 43, 48, 163, 164, 165, 166, 167, 168, 16...   
7     [[2, 41, 45, 49, 57, 77, 82, 89, 109, 116, 152...   
8     [[35, 69, 109, 141, 158, 179, 201, 202, 203, 2...   
9     [[7, 14, 17, 18, 41, 43, 44, 75, 81, 82, 93, 1...   
10    [[2, 19, 23, 30, 41, 48, 52, 96, 112, 148, 161...   
11    [[2, 7, 43, 44, 49, 93, 96, 109, 138, 152, 153...   
12    [[30, 52, 65, 110, 138, 140, 154, 283, 284, 28...   
13    [[2, 23, 43, 52, 58, 83, 109, 129, 152, 161, 1...   
14    [[12, 16, 22, 35, 41, 43, 45, 48, 63, 65, 81, ...   
15    [[2, 12, 15, 19, 22, 41, 43, 93, 95, 106, 109,...   
16    [[2, 12, 15, 23, 30, 43, 58, 87, 89, 153, 154,...   
17    [[23, 32, 41, 43, 45, 48, 82, 89, 96, 109, 116...   
18    [[2, 12, 41, 44, 69, 84, 91, 112, 129, 137, 15...   
19    [[2, 12, 35, 48, 89, 96, 109, 138, 143, 154, 1...   
20    [[12, 23, 26, 36, 41, 43, 48, 116, 133, 138, 1...   
21    [[7, 12, 14, 23, 25, 26, 30, 43, 45, 48, 60, 9...   
22    [[2, 17, 21, 43, 44, 69, 74, 81, 82, 93, 109, ...   
23    [[32, 107, 222, 223, 257, 268, 293, 312, 438, ...   
24    [[89, 137, 161, 215, 313, 544, 545, 546, 547, ...   
25    [[9, 12, 14, 15, 28, 37, 43, 69, 75, 89, 154, ...   
26    [[12, 21, 41, 43, 77, 93, 96, 105, 110, 116, 1...   
27    [[2, 6, 12, 14, 22, 27, 30, 35, 38, 40, 41, 43...   
28    [[43, 44, 45, 57, 138, 192, 223, 242, 267, 268...   
29    [[2, 22, 27, 28, 37, 41, 43, 52, 68, 75, 89, 1...   
...                                                 ...   
2470  [[2, 6, 12, 14, 19, 23, 26, 30, 37, 49, 72, 13...   
2471  [[2, 12, 17, 19, 41, 48, 49, 79, 89, 93, 96, 1...   
2472  [[2, 12, 52, 148, 158, 201, 207, 236, 251, 263...   
2473  [[22, 41, 89, 93, 115, 138, 173, 181, 182, 191...   
2474                     [[43, 52, 93, 223, 420, 1455]]   
2475  [[12, 14, 43, 89, 96, 105, 110, 116, 138, 161,...   
2476  [[12, 13, 23, 43, 82, 89, 93, 138, 198, 210, 6...   
2477  [[2, 12, 23, 39, 43, 44, 52, 78, 89, 96, 101, ...   
2478  [[14, 15, 26, 38, 43, 79, 84, 154, 158, 182, 1...   
2479  [[2, 93, 109, 161, 166, 197, 295, 610, 631, 95...   
2480  [[14, 48, 75, 89, 133, 161, 190, 263, 344, 437...   
2481  [[2, 14, 41, 48, 60, 74, 76, 81, 82, 93, 96, 9...   
2482  [[181, 191, 201, 290, 437, 607, 648, 808, 1260...   
2483  [[32, 45, 116, 129, 161, 175, 372, 396, 415, 4...   
2484  [[74, 75, 93, 96, 144, 167, 179, 190, 210, 220...   
2485  [[2, 7, 22, 49, 79, 96, 138, 152, 163, 215, 30...   
2486  [[12, 18, 62, 74, 93, 96, 152, 161, 181, 220, ...   
2487  [[2, 43, 48, 62, 93, 96, 109, 116, 141, 160, 1...   
2488  [[2, 12, 89, 93, 109, 152, 182, 209, 225, 287,...   
2489                                        [[35, 112]]   
2490  [[12, 23, 35, 43, 44, 68, 74, 81, 82, 83, 89, ...   
2491  [[2, 12, 41, 43, 44, 58, 91, 112, 133, 140, 16...   
2492  [[2, 12, 43, 48, 184, 215, 237, 244, 250, 263,...   
2493  [[2, 49, 107, 161, 175, 408, 631, 1221, 1327, ...   
2494  [[12, 41, 83, 93, 105, 109, 143, 152, 175, 195...   
2495  [[2, 12, 15, 37, 43, 52, 58, 112, 129, 143, 16...   
2496  [[32, 43, 44, 112, 129, 223, 236, 249, 293, 30...   
2497  [[2, 43, 84, 133, 138, 161, 190, 198, 215, 300...   
2498  [[6, 12, 28, 30, 41, 57, 112, 129, 138, 161, 1...   
2499  [[41, 93, 109, 112, 123, 134, 138, 140, 149, 1...   

                                                 counts  
0                                     [[1, 1, 1, 1, 1]]  
1     [[1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1,...  
2     [[2, 2, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1,...  
3     [[3, 1, 1, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,...  
4     [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...  
5     [[2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 3, 1

## Saving The Files

In [22]:
path = "data/drug_review/"

In [23]:
# train.to_csv(path+"train.csv",index=None)
# test.to_csv(path+"test.csv",index=None)
# valid.to_csv(path+"valid.csv",index=None)
dictionary.save(path+"vocab.pkl")

In [24]:
def store_bow_files(df,filename):
    tokens = df.tokens.tolist()
    counts = df.counts.tolist()
    dict_ = {"tokens":tokens,"counts":counts}
    with open(path+filename+'.pkl', 'wb') as handle:
        pickle.dump(dict_, handle)


In [25]:
store_bow_files(train,"train_dict")
store_bow_files(test,"test_dict")
store_bow_files(test_1,"test_1_dict")
store_bow_files(test_2,"test_2_dict")
store_bow_files(valid,"valid_dict")

## Validating The stored Files

In [26]:
with open(path + 'train_dict.pkl', 'rb') as handle:
    train = pickle.load(handle)
train

{'tokens': [array([[0, 1, 2, 3, 4]]),
  array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
          21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
          37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
  array([[ 2, 12, 21, 22, 37, 41, 43, 44, 48, 50, 51, 52, 53, 54, 55, 56,
          57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
          73, 74, 75, 76, 77, 78, 79, 80]]),
  array([[12, 62, 71, 74, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
          93, 94, 95, 96]]),
  array([[ 22,  23,  41,  49,  96,  97,  98,  99, 100, 101, 102, 103, 104,
          105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
          118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
          131, 132, 133, 134, 135, 136, 137, 138, 139]]),
  array([[  2,  12,  41,  48,  93, 140, 141, 142, 143, 144, 145, 146, 147,
          148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
          161, 162]]

In [27]:
with open(path + 'test_dict.pkl', 'rb') as handle:
    test = pickle.load(handle)
test

{'tokens': [array([[0, 1, 2, 3, 4]]),
  array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
          21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
          37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
  array([[ 2, 12, 21, 22, 37, 41, 43, 44, 48, 50, 51, 52, 53, 54, 55, 56,
          57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
          73, 74, 75, 76, 77, 78, 79, 80]]),
  array([[12, 62, 71, 74, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
          93, 94, 95, 96]]),
  array([[ 22,  23,  41,  49,  96,  97,  98,  99, 100, 101, 102, 103, 104,
          105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
          118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
          131, 132, 133, 134, 135, 136, 137, 138, 139]]),
  array([[  2,  12,  41,  48,  93, 140, 141, 142, 143, 144, 145, 146, 147,
          148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
          161, 162]]

In [28]:
with open(path + 'valid_dict.pkl', 'rb') as handle:
    valid = pickle.load(handle)
valid

{'tokens': [array([[   12,    22,    27,    43,    45,    48,    75,   152,   161,
            203,   283,   377,   404,   504,   743,   758,   792,   957,
            967,  1030,  1134,  1184,  1305,  1344,  1983,  2459,  3047,
           4021,  5047,  7961, 10013, 14709, 18769, 18770]]),
  array([[    2,    13,    22,    23,    48,    52,    63,    75,    89,
             93,    96,   102,   109,   114,   152,   182,   188,   195,
            196,   202,   263,   276,   287,   311,   325,   335,   375,
            389,   404,   586,   613,   655,   665,   667,   737,   866,
            890,   983,   988,  1014,  1302,  1327,  1452,  1485,  1494,
           2683,  2834,  3722, 17241]]),
  array([[   2,   26,   30,   43,   48,  129,  152,  154,  178,  211,  278,
           327,  448,  590,  720,  802,  883, 1260, 1682, 1839, 2239, 2639,
          3108, 3223, 3727]]),
  array([[  74,   93,  201,  220,  250,  287,  295,  376,  573,  574,  600,
           932, 2115]]),
  array([[ 16,  89,